# Workflow name, if not set, the configuration file name will be taken by default
name: Build and Deploy
# Specify the conditions that trigger workflow
# Specify the trigger event, you can limit the branch or label
# Currently, workflow tasks are executed only when the push event is triggered on the master branch
on: 
  push:
    branches:
      - master
# One or more tasks performed by the workflow
jobs:
  # mission name
  build-and-deploy:
    # The type of container the task runs (virtual machine environment)
    runs-on: ubuntu-latest
    # Task execution steps
    steps:
      # Step name
      - name: Checkout ️
        # Actions used actions, you can use public warehouses, local warehouses, other people's warehouse actions
        # Pull code
        uses: actions/checkout@master

      - name: Build and Deploy
        # Build and publish Github pages
        uses: crazy-max/ghaction-github-status@v3
        # Environment variables required for this step
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          
